### Crepe the files we want

In [ ]:
'''This function uses CREPE to individually evaluate pitch for each of the voices commonly used during evaluations.'''

import os

tags = [
    'El_Rossinyol/audio_16kHz/rossinyol_Bajos_207.wav',
	'El_Rossinyol/audio_16kHz/rossinyol_ContraAlt_2-06.wav',
	'El_Rossinyol/audio_16kHz/rossinyol_Soprano_208.wav',
	'El_Rossinyol/audio_16kHz/rossinyol_Tenor2-09.wav',
    'Locus_Iste/audio_16kHz/locus_Bajos_3-02.wav',
	'Locus_Iste/audio_16kHz/locus_ContraAlt_301.wav',
	'Locus_Iste/audio_16kHz/locus_Soprano_310.wav',
	'Locus_Iste/audio_16kHz/locus_tenor3-01-2.wav',
    'Nino_Dios/audio_16kHz/nino_Bajos_404.wav',
	'Nino_Dios/audio_16kHz/nino_ContraAlt_407.wav',
	'Nino_Dios/audio_16kHz/nino_Soprano_405.wav',
	'Nino_Dios/audio_16kHz/nino_tenor4-06-2.wav',
        ]

for tag in tags:
	print("crepe ../../Dataset/ChoralSingingDataset/{} --step-size 16".format(tag))
	os.system("crepe ../../Dataset/ChoralSingingDataset/{} --step-size 16".format(tag))
#the --no-centering flag isn't appropriate!


### Crepe CSV to npy

In [1]:
import csv
import glob
import os

import numpy as np

In [2]:
path_to_dataset = '../Datasets/ChoralSingingDataset'
songs = ['El_Rossinyol', 'Locus_Iste', 'Nino_Dios']

In [3]:
for i, song in enumerate(songs):
    path_to_f0_csv_files = os.path.join(path_to_dataset, song, 'audio_16kHz')
    path_to_save_f0_estimate_tensors = os.path.join(path_to_dataset, song, 'crepe_f0_center')

    # make directory to save processed f0 estimates as torch tensor
    if not os.path.isdir(path_to_save_f0_estimate_tensors):
        os.makedirs(path_to_save_f0_estimate_tensors, exist_ok=True)
        
    f0_csv_files = sorted(list(glob.glob(path_to_f0_csv_files + '/*.csv')))
    
    for f0_csv_file in f0_csv_files:
        print(f0_csv_file)
        time = []
        confidence = []
        frequency = []
        with open(f0_csv_file, newline='') as csv_file:
            reader = csv.reader(csv_file, delimiter=',', quotechar='|')
            for i, row in enumerate(reader):
                if i == 0:
                    pass
                else:
                    time.append(float(row[0]))
                    frequency.append(float(row[1]))
                    confidence.append(float(row[2]))
            np.save(path_to_save_f0_estimate_tensors + '/' + f0_csv_file.split('/')[-1].split('.')[0] + '_time.npy', np.array(time, dtype=np.float32))
            np.save(path_to_save_f0_estimate_tensors + '/' + f0_csv_file.split('/')[-1].split('.')[0] + '_frequency.npy', np.array(frequency, dtype=np.float32))
            np.save(path_to_save_f0_estimate_tensors + '/' + f0_csv_file.split('/')[-1].split('.')[0] + '_confidence.npy', np.array(confidence, dtype=np.float32))
                

../Datasets/ChoralSingingDataset/El_Rossinyol/audio_16kHz/rossinyol_Bajos_107.f0.csv
../Datasets/ChoralSingingDataset/El_Rossinyol/audio_16kHz/rossinyol_Bajos_207.f0.csv
../Datasets/ChoralSingingDataset/El_Rossinyol/audio_16kHz/rossinyol_Bajos_307.f0.csv
../Datasets/ChoralSingingDataset/El_Rossinyol/audio_16kHz/rossinyol_Bajos_407.f0.csv
../Datasets/ChoralSingingDataset/El_Rossinyol/audio_16kHz/rossinyol_ContraAlt_1-06.f0.csv
../Datasets/ChoralSingingDataset/El_Rossinyol/audio_16kHz/rossinyol_ContraAlt_2-06.f0.csv
../Datasets/ChoralSingingDataset/El_Rossinyol/audio_16kHz/rossinyol_ContraAlt_3-06.f0.csv
../Datasets/ChoralSingingDataset/El_Rossinyol/audio_16kHz/rossinyol_ContraAlt_4-06.f0.csv
../Datasets/ChoralSingingDataset/El_Rossinyol/audio_16kHz/rossinyol_Soprano_108.f0.csv
../Datasets/ChoralSingingDataset/El_Rossinyol/audio_16kHz/rossinyol_Soprano_208.f0.csv
../Datasets/ChoralSingingDataset/El_Rossinyol/audio_16kHz/rossinyol_Soprano_308.f0.csv
../Datasets/ChoralSingingDataset/El_Ros

### Test crepe

In [4]:
a = np.load('/home/ids/chouteau/umss/Datasets/BC/crepe_f0_center/1_BC001_part1_a_1ch_frequency.npy')

In [5]:
a

array([176.82805402, 177.94420967, 178.0085828 , 180.92943831,
       181.05844143, 179.60595338, 181.79830816, 181.62052161,
       179.8551888 , 179.32959495, 179.63799004, 179.64458891,
       180.94824929, 179.55151721, 179.33918164, 181.45143795,
       181.43859484, 180.81884274, 181.34554979, 181.34843727,
       181.0689747 , 181.10898356, 179.94340494, 180.72241046,
       181.61295791, 179.86635724, 179.87435682, 179.42621775,
       179.07466558, 180.05908422, 179.62104753, 179.83757347,
       180.30342197, 180.30027076, 180.72707391, 180.67133401,
       178.07505514, 179.57432196, 180.98316858, 180.83093495,
       180.54061869, 180.52777572, 179.5643723 , 180.67031125,
       181.56635629, 181.24303113, 180.72122146, 181.02844507,
       179.69340202, 180.40263672, 180.38038851, 180.99380433,
       181.20675896, 180.24950457, 180.05252458, 180.62191976,
       180.40882919, 180.38172267, 180.29223306, 180.05156469,
       181.20433036, 180.13087639, 179.99497738, 179.97

In [14]:
b = np.load('/home/ids/chouteau/umss/Datasets/ChoralSingingDataset/El_Rossinyol/crepe_f0_center/rossinyol_ContraAlt_2-06_time.npy')

In [15]:
b

array([0.00000e+00, 1.60000e-02, 3.20000e-02, ..., 1.35328e+02,
       1.35344e+02, 1.35360e+02], dtype=float32)

### Crepe process for BC, BQ dataset

In [10]:
path_to_dataset = '../Datasets/BQ'
# path_to_dataset = '../Datasets/BC'

In [11]:
path_to_f0_csv_files = os.path.join(path_to_dataset, 'audio_16kHz')
path_to_save_f0_estimate_tensors = os.path.join(path_to_dataset, 'crepe_f0_center')

# make directory to save processed f0 estimates as torch tensor
if not os.path.isdir(path_to_save_f0_estimate_tensors):
    os.makedirs(path_to_save_f0_estimate_tensors, exist_ok=True)
    
f0_csv_files = sorted(list(glob.glob(path_to_f0_csv_files + '/*.csv')))

for f0_csv_file in f0_csv_files:
    print(f0_csv_file)
    time = []
    confidence = []
    frequency = []
    with open(f0_csv_file, newline='') as csv_file:
        reader = csv.reader(csv_file, delimiter=',', quotechar='|')
        for i, row in enumerate(reader):
            if i == 0:
                pass
            else:
                time.append(float(row[0]))
                frequency.append(float(row[1]))
                confidence.append(float(row[2]))
        np.save(path_to_save_f0_estimate_tensors + '/' + f0_csv_file.split('/')[-1].split('.')[0] + '_time.npy', np.array(time, dtype=np.float32))
        np.save(path_to_save_f0_estimate_tensors + '/' + f0_csv_file.split('/')[-1].split('.')[0] + '_frequency.npy', np.array(frequency, dtype=np.float32))
        np.save(path_to_save_f0_estimate_tensors + '/' + f0_csv_file.split('/')[-1].split('.')[0] + '_confidence.npy', np.array(confidence, dtype=np.float32))
                

../Datasets/BQ/audio_16kHz/10_BQ019_part10_a_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part10_b_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part10_s_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part10_t_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part11_a_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part11_b_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part11_s_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part11_t_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part12_a_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part12_b_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part12_s_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part12_t_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part1_a_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part1_b_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part1_s_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part1_t_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part2_a_1ch.f0.csv
../Datasets/BQ/audio_16kHz/10_BQ019_part2_b_1ch.f0.cs

In [18]:
test = np.load('/home/ids/chouteau/umss/Datasets/BQ/crepe_f0_center/1_BQ002_part1_a_1ch_confidence.npy')

In [19]:
test

array([0.106122, 0.068596, 0.481546, 0.410632, 0.552482, 0.816606,
       0.815283, 0.63638 , 0.819093, 0.812598, 0.556617, 0.625108,
       0.411798, 0.837095, 0.634056, 0.823734, 0.858634, 0.74815 ,
       0.719961, 0.454776, 0.826718, 0.503632, 0.404169, 0.777349,
       0.87425 , 0.861501, 0.746376, 0.830234, 0.842236, 0.796659,
       0.271537, 0.516969, 0.876253, 0.759922, 0.450161, 0.388723,
       0.308557, 0.734385, 0.77908 , 0.546955, 0.522628, 0.641743,
       0.659166, 0.77288 , 0.654425, 0.658383, 0.658832, 0.267583,
       0.019298, 0.073744, 0.126711, 0.23755 , 0.066687, 0.224451,
       0.489751, 0.161842, 0.205904, 0.130486, 0.115818, 0.318395,
       0.127832, 0.13388 , 0.057102, 0.262572, 0.237295, 0.079118,
       0.05913 , 0.019542, 0.054588, 0.072122, 0.088726, 0.112409,
       0.152819, 0.119424, 0.351583, 0.072649, 0.301108, 0.240199,
       0.260049, 0.25946 , 0.1073  , 0.123367, 0.205592, 0.048826,
       0.302547, 0.218022, 0.10781 , 0.16638 , 0.195647, 0.069