In [1]:
import torch

In [4]:
f0_estimates = torch.load("/home/ids/chouteau/umss/Datasets/BC/mixtures_4_sources/mf0_cuesta_processed/1_BC001_part1_satb.pt")
# f0_estimates_test = torch.load("/home/pchouteau/umss/archive/Datasets/BC/mixtures_tests/mf0_cuesta_processed/1_BC001_part13_satb.pt")

# torch.min(f0_estimates - f0_estimates_test, dim=0)

In [7]:
f0_estimates[90:100], f0_estimates[-4:]

(tensor([[  0.0000, 369.2240, 280.3759, 240.7990],
         [  0.0000, 365.7089, 280.3759, 238.5066],
         [  0.0000, 361.8109, 283.3992, 241.0784],
         [  0.0000, 361.5084, 283.6338, 242.1347],
         [  0.0000, 361.5084, 285.8853, 244.0814],
         [  0.0000, 365.7089, 286.9294, 246.9175],
         [  0.0000, 365.7089, 286.9294, 246.9175],
         [  0.0000, 365.7089, 286.9294, 246.9175],
         [492.7370, 366.5315, 286.2914, 246.9175],
         [488.1629, 369.9583, 283.6338, 245.2976]]),
 tensor([[537.4304, 365.7089, 241.2779, 178.6781],
         [  0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000],
         [  0.0000,   0.0000,   0.0000,   0.0000]]))

In [98]:
f0_estimates_test[0:3], f0_estimates_test[-4:]

(tensor([[488.1629,   0.0000, 329.5953, 180.3622],
         [488.1629, 166.0709, 333.9589, 178.6781],
         [488.1629,   0.0000, 333.6420, 180.6380]]),
 tensor([[558.6802, 365.7089, 240.3865, 180.7542],
         [560.7519, 365.7089, 238.3533, 180.8718],
         [560.7519, 365.7089, 235.7671, 182.8545],
         [566.0371,   0.0000, 235.7671, 182.8545]]))

In [8]:
ind = 50

f0_estimates_test[ind]

tensor([0., 0., 0., 0.])

In [9]:
f0_estimates_test.shape

torch.Size([625, 4])